#!/bin/bash
#
# Copyright 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Avoid D8 merge in the default script since it would reject the class.
# Use old API level to create DEX file with 035 version. Stricter
# checking introduced with DEX file version 37 rejects class
# otherwise (see DexFile::kClassDefinitionOrderEnforcedVersion).
${SMALI} -JXmx512m assemble --api 13 --output classes.dex `find smali -name '*.smali'`
${SOONG_ZIP} -o $TEST_NAME.jar -f classes.dex
