#!/bin/bash
#
# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

# This test depends on the exact format of the DEX file. Since dx is deprecated,
# the classes.dex file is packaged as a test input. See src/Main.java file
# to check how it was created.

# Wrapper function for javac which for this test does nothing as the
# test uses a pre-built DEX file.
cat >javac_wrapper.sh <<"EOF"
  return 0
EOF
export JAVAC=./javac_wrapper.sh

# Do not invoke D8 for this test.
export D8=':'

######################################################################

${SOONG_ZIP} --jar -o classes.jar -f classes.dex
./default-build "$@"
