%def binop(preinstr="", result="r0", chkzero="0", instr=""):
    unimp

%def binop2addr(preinstr="", result="r0", chkzero="0", instr=""):
    unimp

%def binopLit16(result="r0", chkzero="0", instr=""):
    unimp

%def binopLit8(extract="unimp", result="r0", chkzero="0", instr=""):
    unimp

%def binopWide(preinstr="", result0="r0", result1="r1", chkzero="0", instr=""):
    unimp

%def binopWide2addr(preinstr="", result0="r0", result1="r1", chkzero="0", instr=""):
    unimp

%def unop(preinstr="", instr=""):
    unimp

%def unopNarrower(preinstr="", instr=""):
    unimp

%def unopWide(preinstr="", instr=""):
    unimp

%def unopWider(preinstr="", instr=""):
    unimp

%def op_add_int():
    unimp

%def op_add_int_2addr():
    unimp

%def op_add_int_lit16():
    unimp

%def op_add_int_lit8():
    unimp

%def op_add_long():
    unimp

%def op_add_long_2addr():
    unimp

%def op_and_int():
    unimp

%def op_and_int_2addr():
    unimp

%def op_and_int_lit16():
    unimp

%def op_and_int_lit8():
    unimp

%def op_and_long():
    unimp

%def op_and_long_2addr():
    unimp

%def op_cmp_long():
    unimp

%def op_div_int():
    unimp

%def op_div_int_2addr():
    unimp

%def op_div_int_lit16():
    unimp

%def op_div_int_lit8():
    unimp

%def op_div_long():
    unimp

%def op_div_long_2addr():
    unimp

%def op_int_to_byte():
    unimp

%def op_int_to_char():
    unimp

%def op_int_to_long():
    unimp

%def op_int_to_short():
    unimp

%def op_long_to_int():
    unimp

%def op_mul_int():
    unimp

%def op_mul_int_2addr():
    unimp

%def op_mul_int_lit16():
    unimp

%def op_mul_int_lit8():
    unimp

%def op_mul_long():
    unimp

%def op_mul_long_2addr():
    unimp

%def op_neg_int():
    unimp

%def op_neg_long():
    unimp

%def op_not_int():
    unimp

%def op_not_long():
    unimp

%def op_or_int():
    unimp

%def op_or_int_2addr():
    unimp

%def op_or_int_lit16():
    unimp

%def op_or_int_lit8():
    unimp

%def op_or_long():
    unimp

%def op_or_long_2addr():
    unimp

%def op_rem_int():
    unimp

%def op_rem_int_2addr():
    unimp

%def op_rem_int_lit16():
    unimp

%def op_rem_int_lit8():
    unimp

%def op_rem_long():
    unimp

%def op_rem_long_2addr():
    unimp

%def op_rsub_int():
    unimp

%def op_rsub_int_lit8():
    unimp

%def op_shl_int():
    unimp

%def op_shl_int_2addr():
    unimp

%def op_shl_int_lit8():
    unimp

%def op_shl_long():
    unimp

%def op_shl_long_2addr():
    unimp

%def op_shr_int():
    unimp

%def op_shr_int_2addr():
    unimp

%def op_shr_int_lit8():
    unimp

%def op_shr_long():
    unimp

%def op_shr_long_2addr():
    unimp

%def op_sub_int():
    unimp

%def op_sub_int_2addr():
    unimp

%def op_sub_long():
    unimp

%def op_sub_long_2addr():
    unimp

%def op_ushr_int():
    unimp

%def op_ushr_int_2addr():
    unimp

%def op_ushr_int_lit8():
    unimp

%def op_ushr_long():
    unimp

%def op_ushr_long_2addr():
    unimp

%def op_xor_int():
    unimp

%def op_xor_int_2addr():
    unimp

%def op_xor_int_lit16():
    unimp

%def op_xor_int_lit8():
    unimp

%def op_xor_long():
    unimp

%def op_xor_long_2addr():
    unimp
