%def fbinop(instr=""):
    unimp

%def fbinop2addr(instr=""):
    unimp

%def fbinopWide(instr=""):
    unimp

%def fbinopWide2addr(instr=""):
    unimp

%def funop(instr=""):
    unimp

%def funopNarrower(instr=""):
    unimp

%def funopWider(instr=""):
    unimp

%def op_add_double():
    unimp

%def op_add_double_2addr():
    unimp

%def op_add_float():
    unimp

%def op_add_float_2addr():
    unimp

%def op_cmpg_double():
    unimp

%def op_cmpg_float():
    unimp

%def op_cmpl_double():
    unimp

%def op_cmpl_float():
    unimp

%def op_div_double():
    unimp

%def op_div_double_2addr():
    unimp

%def op_div_float():
    unimp

%def op_div_float_2addr():
    unimp

%def op_double_to_float():
    unimp

%def op_double_to_int():
    unimp

%def op_double_to_long():
    unimp

%def op_float_to_double():
    unimp

%def op_float_to_int():
    unimp

%def op_float_to_long():
    unimp

%def op_int_to_double():
    unimp

%def op_int_to_float():
    unimp

%def op_long_to_double():
    unimp

%def op_long_to_float():
    unimp

%def op_mul_double():
    unimp

%def op_mul_double_2addr():
    unimp

%def op_mul_float():
    unimp

%def op_mul_float_2addr():
    unimp

%def op_neg_double():
    unimp

%def op_neg_float():
    unimp

%def op_rem_double():
    unimp

%def op_rem_double_2addr():
    unimp

%def op_rem_float():
    unimp

%def op_rem_float_2addr():
    unimp

%def op_sub_double():
    unimp

%def op_sub_double_2addr():
    unimp

%def op_sub_float():
    unimp

%def op_sub_float_2addr():
    unimp
