%def unused():
    ebreak
%def op_const():
    unimp

%def op_const_16():
    unimp
%def op_const_4():
    unimp
%def op_const_high16():
    unimp
%def op_const_object(jumbo="0", helper="nterp_load_object"):
    unimp
%def op_const_class():
    unimp
%def op_const_method_handle():
    unimp
%def op_const_method_type():
    unimp
%def op_const_string():
    unimp
%def op_const_string_jumbo():
    unimp
%def op_const_wide():
    unimp
%def op_const_wide_16():
    unimp
%def op_const_wide_32():
    unimp
%def op_const_wide_high16():
    unimp
%def op_monitor_enter():
    unimp
%def op_monitor_exit():
    unimp
%def op_move(is_object="0"):
    unimp
%def op_move_16(is_object="0"):
    unimp
%def op_move_exception():
    unimp
%def op_move_from16(is_object="0"):
    unimp
%def op_move_object():
    unimp
%def op_move_object_16():
    unimp
%def op_move_object_from16():
    unimp
%def op_move_result(is_object="0"):
    unimp
%def op_move_result_object():
    unimp
%def op_move_result_wide():
    unimp
%def op_move_wide():
    unimp
%def op_move_wide_16():
    unimp
%def op_move_wide_from16():
    unimp

%def op_nop():
    unimp

%def op_unused_3e():
%  unused()

%def op_unused_3f():
%  unused()

%def op_unused_40():
%  unused()

%def op_unused_41():
%  unused()

%def op_unused_42():
%  unused()

%def op_unused_43():
%  unused()

%def op_unused_73():
%  unused()

%def op_unused_79():
%  unused()

%def op_unused_7a():
%  unused()

%def op_unused_e3():
%  unused()

%def op_unused_e4():
%  unused()

%def op_unused_e5():
%  unused()

%def op_unused_e6():
%  unused()

%def op_unused_e7():
%  unused()

%def op_unused_e8():
%  unused()

%def op_unused_e9():
%  unused()

%def op_unused_ea():
%  unused()

%def op_unused_eb():
%  unused()

%def op_unused_ec():
%  unused()

%def op_unused_ed():
%  unused()

%def op_unused_ee():
%  unused()

%def op_unused_ef():
%  unused()

%def op_unused_f0():
%  unused()

%def op_unused_f1():
%  unused()

%def op_unused_f2():
%  unused()

%def op_unused_f3():
%  unused()

%def op_unused_f4():
%  unused()

%def op_unused_f5():
%  unused()

%def op_unused_f6():
%  unused()

%def op_unused_f7():
%  unused()

%def op_unused_f8():
%  unused()

%def op_unused_f9():
%  unused()

%def op_unused_fc():
%  unused()

%def op_unused_fd():
%  unused()

