#! /bin/bash
#
# Copyright 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
  cat >&2 <<EOF
Determine and print the 32- or 64-bit architecture of a device.

Usage:
  $0 --32    Select the 32-bit architecture
  $0 --64    Select the 64-bit architecture
EOF
  exit 1
}

check_32bit() {
  if ! adb shell test -e /system/bin/linker; then
    echo >&2 "Device does not have 32-bit support"
    exit 1
  fi
}

if [[ $# -ne 1 ]]; then
  usage
fi

uname_m="$(adb shell uname -m)"

case "$1" in
  (--32)
    case $uname_m in
      (armv*)
        echo arm
        ;;
      (i?86)
        echo x86
        ;;
      (aarch64)
        check_32bit
        echo arm
        ;;
      (x86_64)
        check_32bit
        echo x86
        ;;
      (*)
        echo >&2 "Unknown ISA: $uname_m"
        exit 1
    esac
    ;;
  (--64)
    case $uname_m in
      (aarch64)
        echo arm64
        ;;
      (x86_64)
        echo x86_64
        ;;
      (*)
        echo >&2 "Unknown ISA: $uname_m"
        exit 1
    esac
    ;;
  (*) usage;;
esac
